### PR TITLE
Validate password correctly on reset

### PR DESCRIPTION
**Pull request by vnc-kber**
Thank you for the extensions, this resolves issue #12

### CODE REVIEW

**Comment by Mainbird** [comment]
Hi @vnc-kber , thanks for your PR. :)
I will discuss your changes with my team next few days because I think we will drop TYPO3 9 support soon. So we have to do some other adjustments as well. Furthermore, Github is only a mirror so I can't directly merge your PR yet, but maybe we can create another release with your changes inside for TYPO3 9+, before we release a new version for TYPO3 10+.

**Comment by vnc-kber** [comment]
Hi @Mainbird, my PR is for TYPO3 10+ only, TYPO3 v.9 does not have password reset function.

**Comment by Mainbird** [comment]
Hi @vnc-kber , yeah I know :) ... But we can drop the version check inside ext_localconf.php, if we drop the TYPO3 9 support with the next release as well :)

**Comment by Mainbird** [comment]
Hi @vnc-kber I am working on the next release now. :) 

Today, I have checked your PR, but I think we need some visual feedback for the user as well, because if the user enter a new password which doesn't match the me_backend_security password rules then the user will stuck on the password reset page with the core hint: "The password you entered is invalid or the passwords do not match. Please try again."

Furthermore, we should update tx_mebackendsecurity_lastpasswordchange during password reset, because if we not update this value and the user didn't logged in so far, then the user will get a password update prompt during first login. I think this wouldn't be really user friendly.

I am not a big fan of xclassing core classes, but as I can see there are no provider, hooks or events available, so I think we have to use xclasses here. :(

**Comment by Mainbird** [comment]
I have added some visual feedback now, too. So I think I will release a new version next week.

Bildschirmfoto 2021-10-29 um 11 16 55

**Comment by vnc-kber** [comment]
Hi @Mainbird, any news on this? Would be really nice to have this feature released.

**Comment by Mainbird** [comment]
Hi @vnc-kber, I have already created a new tag that is ready to release, but this repo here is only a mirror and currently, there is an issue to sync this repo. I have informed my workmate today, so he will check this as soon as possible.

**Comment by Mainbird** [comment]
Hi @vnc-kber we have released version 2.0.7 today. This release contains the password rules for the password reset form. :)

**Pull request closed without merging**
